### ISSUE TITLE
Is MIT is violating GPL license of geth binaries?

### ISSUE THREAD

**Issue by TimDaub** [ethereum/py-geth#111]
- I haven't checked the code specifically but geth's licensing terms say:

> The go-ethereum binaries (i.e. all code inside of the cmd directory) is licensed under the [GNU General Public License v3.0](https://www.gnu.org/licenses/gpl-3.0.en.html), also included in our repository in the COPYING file.

So how can py-geth be MIT? If it uses the binaries, GPL property is viral and hence py-geth must be GPL too. What am I missing?

This was originally pointed out here: https://github.com/neume-network/documents/issues/11#issuecomment-1229515744

**Comment by kclowes** [comment]
According to GNU, the "MIT License" or the [Expat License](https://www.gnu.org/licenses/license-list.en.html#Expat) is compatible with GPL.

**Comment by TimDaub** [comment]
> According to GNU, the "MIT License" or the [Expat License](https://www.gnu.org/licenses/license-list.en.html#Expat) is compatible with GPL.

I think I wasn't asking whether those licenses were compatible. Rather, I think that py-geth is making geth illegally available under MIT when surely not all its authors have agreed to that (since they licensed their contributions in some cases under GPL). Isn't his package loopholing geth's GPL licensing?
