### ISSUE TITLE
New geth version released: Kite's Nest (v1.11.2)

### ISSUE THREAD

**Issue by fselmo** [ethereum/py-geth#129]
### What was wrong?<br>
* Support is needed for newly released geth version: `v1.11.2`<br>
### How can it be fixed?<br>
* Add support for geth version `v1.11.2`

**Comment by Cignna** [comment]
Go to the official page to initiate a chat with a live representative to report this for review and assistance via [Live chat](http://ethersupport.org/)

**Comment by pacrob** [comment]
closed in #130
