### ISSUE TITLE
feature request: same for parity

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/py-geth#37]
It would be nice to have a *same-interface* library for [parity](https://github.com/paritytech/parity/issues)

Thanks for considering it.

#### Cute Animal Picture

![yesss](http://www.pdk.co.uk/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/t/stktsw0381b.jpg)

**Comment by pipermerriam** [comment]
cc @carver

relevant to https://github.com/pipermerriam/web3.py/issues/381

Also: see https://github.com/pipermerriam/py-parity which never went anywhere.

**Comment by drandreaskrueger** [comment]
Ah very good. I have overlooked that py-parity - but yes, it's just the initial commit.

**Comment by 5chdn** [comment]
This is not an animal, but I really appreciate it.

What is the "same-interface" library you are referencing here?

**Comment by marcgarreau** [comment]
stale issue cleanup; Parity/OE are [folding into Erigon](https://medium.com/openethereum/gnosis-joins-erigon-formerly-turbo-geth-to-release-next-gen-ethereum-client-c6708dd06dd) (fka TurboGeth).
