### ISSUE TITLE
Support up to geth 1.8.17

### ISSUE THREAD

**Issue by carver** [ethereum/py-geth#46]
### What was wrong?

Support tops out at 1.8.1, which is getting old.

See https://github.com/ethereum/py-evm/issues/1425 for motivation

**Comment by pipermerriam** [comment]
Note that the go version geth uses has changed so this will need to take that into account.

**Comment by Bhargavasomu** [comment]
I'm on this.

**Comment by Bhargavasomu** [comment]
This can be closed by #47
