### ISSUE TITLE
Migrate from Travis CI to Circle CI

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/py-geth#48]
### What is wrong?
As we are installing a lot of versions of `geth`, it would be better to migrate to `Circle CI`, as it is a lot faster and does parallel jobs too.

**Comment by Bhargavasomu** [comment]
Giving this a shot.

**Comment by pipermerriam** [comment]
I've enabled this project on CircleCI.  Once a proper config file is present in the project it **should** begin building.
