### ISSUE TITLE
Removing support for Python 2.7

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/py-geth#51]
### What was wrong?

Is it about time to remove support for `Python 2.7`?

#### Cute Animal Picture

![Cute Animal Picture](https://static.boredpanda.com/blog/wp-content/uuuploads/cute-baby-animals-2/cute-baby-animals-2-2.jpg)

**Comment by pipermerriam** [comment]
Yes, seems appropriate.

**Comment by Bhargavasomu** [comment]
So should we show a `Warning` (which we currently do), or raise an exception if using `python 2.7`?

**Comment by carver** [comment]
Ah, too bad this didn't make it into the v2 release. The change would trigger a v3 release. So if we assume this is going to trigger v3, then we can simply drop py2 support by adding the constraint in setup.py. So exceptions are fine :+1:
