### ISSUE TITLE
Document the comparison DevGethProcess with `geth --dev`

### ISSUE THREAD

**Issue by antazoey** [ethereum/py-geth#74]
* `py-geth` Version: master
* `go-ethereum` Version: 1.10.1
* Python Version: 3.9.7
* OS: macOS

### What was wrong?

I am trying to understand `DevGethProcess` and how it compares to `geth --dev`.
From what I can gather, it does the same thing as `geth --dev` except maybe give you a little more control, such as the ability to override genesis configuration. Is this correct? 

By just a quick glance at the class and how it is named, I would assume `DevGethProcess` launches `geth --dev`. I think I am glad it does not since I would like to control the genesis block and not have one get created automatically, but just am a little confused... **Are we able to replicated all of the functionality of geth --dev in a private, local blockchain like this?** If yes, that is amazing.

Some class-code comments might help with this. Something like `Launches a dev geth process (not `geth --dev` but of similar functionality).` Otherwise, one has to inspect the `wrapper.py` to figure out what command is actually be called.

#### Cute Animal Picture

![baby_bear](https://user-images.githubusercontent.com/19540978/138704723-fe32708f-8822-4258-aac5-a170e6ca5557.jpeg)

**Comment by fselmo** [comment]
#195 switches to using `geth --dev` for `DevGethProcess`. It's no longer possible to run a private chain without having a consensus client so in order to launch a development chain, we have to use `geth --dev` which runs with a `SimulatedBeacon`.

**Comment by antazoey** [comment]
I would say #195 closes this issue, as it is much more clear that dev mode uses `--dev` and there is no longer any need to document the difference.
